//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerDroidWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller_Product()
        {
            this.Seller_Product_Rating = new HashSet<Seller_Product_Rating>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Small_Description { get; set; }
        public string Long_Description { get; set; }
        public Nullable<int> Main_Image_Id { get; set; }
        public string Seller_User_Id { get; set; }
       //S public bool Is_Featured { get; set; }
        public bool Is_Visible { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modifed { get; set; }
        public Nullable<double> Average_Rating { get; set; }
        public string Barcode { get; set; }
        public string Keywords { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Seller_File Seller_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_Product_Rating> Seller_Product_Rating { get; set; }
    }
}
