//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerDroidWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller_File()
        {
            this.Seller_Product = new HashSet<Seller_Product>();
            this.Seller_User_Info = new HashSet<Seller_User_Info>();
        }
    
        public int Id { get; set; }
        public string Filename { get; set; }
        public byte[] Content { get; set; }
        public int Content_Length { get; set; }
        public string Content_Type { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_Product> Seller_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_User_Info> Seller_User_Info { get; set; }
    }
}
