//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerDroidWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_User_Info
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Is_Supplier { get; set; }
        public Nullable<double> Map_Latitude { get; set; }
        public Nullable<double> Map_Longitude { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> Picture_Id { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Seller_File Seller_File { get; set; }
    }
}
