//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerDroidWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_Product_Rating
    {
        public int Product_Id { get; set; }
        public string User_Id { get; set; }
        public double Rating { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Seller_Product Seller_Product { get; set; }
    }
}
